Testing new late-failing build

diff --git a/operator-common/verify-build b/operator-common/verify-build
--- a/operator-common/verify-build
+++ b/operator-common/verify-build
@@ -2,8 +2,22 @@
 #to our DevOps results storage in Github, and then inspect the build output to fail if our fail fast criteria have
 #not been met.
 #Currently we only check for Failsafe or Surefire failures, but we may want to extend this to fail on other criteria too
-jx step stash --pattern="target/site/*" --to-path=${REPO_NAME}/$1 -c reports --basedir=target/site
-if grep -rnw target/*-reports/*.xml -e "<failure" || grep -rnw target/*-reports/*.xml -e "<error"; then
-  echo >&2 "Tests failed for ${REPO_NAME}-$1"
+#jx step stash --pattern="target/site/*" --to-path=${REPO_NAME}/$1 -c reports --basedir=target/site
+if grep -rnw target/surefire-reports/*.xml -e "<failure" >/dev/null 2>&1 || grep -rnw target/surefire-reports/*.xml -e "<error" >/dev/null 2>&1; then
+  echo >&2 "Unit tests failed for ${REPO_NAME}-$1."
   exit 1
 fi
+if grep -rnw target/failsafe-reports/*.xml -e "<failure" >/dev/null 2>&1 || grep -rnw target/failsafe-reports/*.xml -e "<error" >/dev/null 2>&1; then
+  echo >&2 "Integration tests failed for ${REPO_NAME}-$1."
+  exit 1
+fi
+if grep -rnw target/checkstyle-result.xml -e "<error" >/dev/null 2>&1; then
+  echo >&2 "Checkstyle rules were violated for ${REPO_NAME}-$1."
+  exit 1
+fi
+if grep -rnw target/site/dependency-check-junit.xml -e "<failure" >/dev/null 2>&1; then
+  echo >&2 "OWASP has found dependencies with vulnerabilities for ${REPO_NAME}-$1."
+  exit 1
+fi
+echo "Congratulations! No build failures found for ${REPO_NAME}-$1."
+
